### PR TITLE
Fixes #3, added basic test for data output.

### LINKED ISSUE #3: Add tests for data
Add a set of test. Some simple serialisation tests should suffice, to ensure there is no crash for incorrectly configured builder for example.

### PR DESCRIPTION
**Pull request by haster**

### CODE REVIEW

File: data/src/test/resources/output.js [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+			        display : true,
+			        scaleLabel : {
+			          display : true,
+			          labelString : "active users"
+			        },
+			        ticks : { },
+			        position : "bottom",
+			        type : "linear"
+			      },
+			      xAxes : [ {
```
Comment (haster) [inline data/src/test/resources/output.js]: Axes are configured twice, once in yAxis, once in yAxes. Is that correct?
